[theme]
primaryColor = "#00f2ff"
backgroundColor = "#0a192f"
secondaryBackgroundColor = "rgba(10, 25, 47, 0.7)"
textColor = "#ffffff"
font = "sans-serif"

[server]
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
